---
# # ansible playbook that adds ssh fingerprints to known_hosts
- hosts: control
  gather_facts: false
  become: true
  tasks:
  - name: Add fingerprints to known_hosts
    command: ssk-keyscan -H {{ item }} >> ~/.ssh/know_hosts
    with_items:
    - s0.infra
    - s1.infra
    - s2.infra
    - s3.infra
    - s4.infra
  - name: Reload service ssh
    service:
      name: ssh
      state: reloaded
    become: true

# # add web/database hosts to known_hosts (IP is defined in Vagrantfile)
# ssh-keyscan -H 192.168.10.11 >> /home/vagrant/.ssh/known_hosts
# ssh-keyscan -H 192.168.10.12 >> /home/vagrant/.ssh/known_hosts
# ssh-keyscan -H 192.168.10.13 >> /home/vagrant/.ssh/known_hosts
# chown vagrant:vagrant /home/vagrant/.ssh/known_hosts

# # reload ssh in order to load the known hosts
# /etc/init.d/ssh reload

- hosts: all
  tasks:
    - name: install tmux
      apt:
        name: ['tmux']
        state: present


