---
- hosts: control
  connection: local
  gather_facts: False
  tasks:
    - name: Make sure the known hosts file exists
      file: "path={{ ssh_known_hosts_file }} state=touch"

    - name: Check host name availability
      shell: "ssh-keygen -f {{ ssh_known_hosts_file }} -F {{ item }}"
      with_items: ssh_known_hosts
      register: ssh_known_host_results
      ignore_errors: yes

    - name: Scan the public key
      shell: "{{ ssh_known_hosts_command}} {{ item.item }} >> {{ ssh_known_hosts_file }}"
      with_items: "{{ ssh_known_host_results.results }}"
      when: item.stdout == ""

      vars:
        ssh_known_hosts_command: "ssh-keyscan -H -T 10"
        ssh_known_hosts_file: "/etc/ssh/ssh_known_hosts"
        ssh_known_hosts:
          - s0.infra
          - s1.infra

# ---
# # ansible playbook that adds ssh fingerprints to known_hosts
# - hosts: all
#   connection: local
#   gather_facts: no
#   tasks:
#   - command: /usr/bin/ssh-keyscan -T 10 {{ ansible_host }}
#     register: keyscan
#   - lineinfile: name=~/.ssh/known_hosts create=yes line={{ item }}
#     with_items: '{{ keyscan.results | map(attribute='stdout_lines') | list }}'

